AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  SnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: email@example.com
          Protocol: email
      TopicName: alarm-action
  CloudWatchAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: no_mfa_api_activity
      AlarmDescription: >-
        A CloudWatch Alarm that triggers if there is API activity in the account
        without MFA (Multi-Factor Authentication).
      MetricName: ApiActivityWithoutMFACount
      Namespace: CloudTrailMetrics
      Statistic: Sum
      Period: '300'
      EvaluationPeriods: '1'
      Threshold: '1'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - Ref: SnsTopic
      TreatMissingData: notBreaching
  MetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Properties:
      LogGroupName: cloudtrail_log_group
      FilterPattern: '{ $.userIdentity.sessionContext.attributes.mfaAuthenticated != "true" }'
      MetricTransformations:
        - MetricValue: '1'
          MetricNamespace: CloudTrailMetrics
          MetricName: ApiActivityWithoutMFACount
Parameters: {}
Metadata: {}
Conditions: {}