AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  EventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-trusted-advisor-events
      Description: >-
        A CloudWatch Event Rule that triggers on changes in the status of AWS
        Trusted Advisor checks, and forwards the events to an SNS topic.
      State: ENABLED
      Targets:
        - Arn:
            Ref: SnsTopic
          Id: target-id1
      EventPattern:
        source:
          - aws.trustedadvisor
  SnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: email@example.com
          Protocol: email
      TopicName: event-rule-action
  SnsTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Sid: __default_statement_ID
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'SNS:GetTopicAttributes'
              - 'SNS:SetTopicAttributes'
              - 'SNS:AddPermission'
              - 'SNS:RemovePermission'
              - 'SNS:DeleteTopic'
              - 'SNS:Subscribe'
              - 'SNS:ListSubscriptionsByTopic'
              - 'SNS:Publish'
              - 'SNS:Receive'
            Resource:
              Ref: SnsTopic
            Condition:
              StringEquals:
                'AWS:SourceOwner':
                  Ref: 'AWS::AccountId'
          - Sid: TrustCWEToPublishEventsToMyTopic
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource:
              Ref: SnsTopic
      Topics:
        - Ref: SnsTopic
Parameters: {}
Metadata: {}
Conditions: {}
