AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  ConfigRule:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      ConfigRuleName: ec2-managedinstance-applications-blacklisted
      Description: >-
        A Config rule that checks that none of the specified applications are
        installed on the instance. Optionally, specify the application version.
        Newer versions of the application will not be blacklisted. You can also
        specify the platform to apply the rule...
      Scope:
        ComplianceResourceTypes:
          - 'AWS::SSM::ManagedInstanceInventory'
      InputParameters:
        applicationNames: asdasd
        platformType: asdasd
      Source:
        Owner: AWS
        SourceIdentifier: EC2_MANAGEDINSTANCE_APPLICATIONS_BLACKLISTED
Parameters: {}
Metadata: {}
Conditions: {}
