AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: sdsdfdfsdf
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              AWS: '*'
            Action:
              - 's3:*'
            Resource:
              - 'arn:aws:s3:::sdsdfdfsdf/*'
              - 'arn:aws:s3:::sdsdfdfsdf'
            Effect: Deny
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
Parameters: {}
Metadata: {}
Conditions: {}
