AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: bucket_name
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Principal:
              AWS:
                - iam_user_or_role
            Action: 's3:*'
            Resource:
              - 'arn:aws:s3:::bucket_name/*'
              - 'arn:aws:s3:::bucket_name'
            Effect: Allow
          - NotPrincipal:
              AWS:
                - iam_user_or_role
            Action: 's3:*'
            Resource:
              - 'arn:aws:s3:::bucket_name/*'
              - 'arn:aws:s3:::bucket_name'
            Effect: Deny
Parameters: {}
Metadata: {}
Conditions: {}